### ISSUE TITLE
Decap CMS - change commit's author to someone other than DoomHammer

### ISSUE THREAD

**Issue by MartaSien** [hs3city/hs3.pl#104]
### Description of the issue
Currently, when creating a new PR via Decap CMS, the author is always @DoomHammer . 
Sample PR with the issue: [Create [ENG] Projects “żeton”](https://github.com/hs3city/hs3.pl/pull/101)

### How it should be?
When opening a PR via Decap CMS, the author should be, if possible, a creator of the PR. If it's not possible, perhaps the author could be something akin to a faceless account.

### Useful info

- [PR where Decap was implemented](https://github.com/hs3city/hs3.pl/pull/92)
- [Discussion on the issue on Discord](https://discord.com/channels/762566311930101761/1112390625044734044/1213423442959933441)
- [Decap CMS documentation](https://decapcms.org/docs/intro/)

### Implementation plan
- [x] Research the docs on available options
- [x] Decide on the potential solution and test it via fork
- [x] Get the solution approved
- [x] Open a PR and implement the solution -> https://github.com/hs3city/hs3.pl/pull/108
- [x] Change path of images to reflect current directory structure (currently it creates a [nested static folder](https://github.com/hs3city/hs3.pl/pull/110/files#diff-0c7105c5ced800fc6bd3f19ad2f0cb4afa1d542cb2408d42bc74946a3d2f77ec)) -> https://github.com/hs3city/hs3.pl/pull/113 & https://github.com/hs3city/hs3.pl/pull/115
- [x] Announce that Decap CMS is ready and invite everyone to use it 🎉 [announced on Discord](https://discord.com/channels/762566311930101761/762566312420442137/1302328647742525460)

**Comment by MartaSien** [comment]
One option is to change the `backend` to `GitHub`. This way, a user will have to authorize via their GitHub account to use Decap CMS dashboard.
I tested creating the PR and it worked: https://github.com/MartaSien/hs3.pl/pull/18
It can even create a fork automatically.

The process is described [in docs here](https://docs.netlify.com/security/secure-access-to-sites/oauth-provider-tokens/#enable-oauth-for-a-netlify-site).

**Comment by MartaSien** [comment]
Issues with Decap CMS were fixed here:
- https://github.com/hs3city/hs3.pl/pull/108
- https://github.com/hs3city/hs3.pl/pull/113
